export const USER_GET = "USER_GET";
export const USER_LOADING = "USER_LOADING";
export const USER_ERROR = "USER_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";
export const CHECK_AUTH = "CHECK_AUTH";

export const APPOINTMENT_GET = "APPOINTMENT_GET";
export const APPOINTMENTS_DAILY_GET = "APPOINTMENTS_DAILY_GET";
export const APPOINTMENTS_MONTHLY_GET = "APPOINTMENTS_MONTHLY_GET";
export const APPOINTMENT_LOADING = "APPOINTMENT_LOADING";
export const APPOINTMENT_ERROR = "APPOINTMENT_ERROR";
